# Generated by Django 5.1.2 on 2024-10-17 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generos',
            fields=[
                ('generos_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_genero', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('usuarios_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuarios', models.CharField(max_length=255)),
                ('fk_genero', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apli.generos')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
